# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: v1
appVersion: "4.0.0_04"
description: A Helm chart for Kubernetes
name: key-rotation
version: 1.0.0
maintainers:
- name: Gluu
email: support@gluu.org
home: https://www.gluu.org
