kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "oxtrust.fullname" . }}-cm
data:
  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName | quote }}
  GLUU_SECRET_ADAPTER: {{ .Values.global.configSecretAdapter | quote }}
  GLUU_LDAP_URL: {{ .Values.global.gluuLdapUrl | quote }}
  GLUU_MAX_RAM_FRACTION: {{ .Values.gluuMaxRamFraction | quote }}
  DOMAIN: {{ .Values.global.domain | quote }}
  GLUU_OXAUTH_BACKEND: {{ .Values.gluuOxauthBackend | quote }}
