# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Service
metadata:
  name: oxtrust
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "oxtrust.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http-oxtrust
  selector:
    app: {{ include "oxtrust.name" . }}
  clusterIP: {{ .Values.service.clusterIp }}