# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "oxtrust.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "oxtrust.labels" . | indent 4 }}
spec:
  serviceName: oxtrust
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "oxtrust.name" . }}
      APP_NAME: oxtrust
  template:
    metadata:
      labels: 
        app: {{ include "oxtrust.name" . }}
        APP_NAME: oxtrust
    spec:
      containers:
      - name: {{ include "oxtrust.name" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python3 /scripts/updatelbip.py &
              /app/scripts/entrypoint.sh
        {{- end }}
        {{- if or (eq .Values.global.provisioner "microk8s.io/hostpath" ) (eq .Values.global.provisioner "k8s.io/minikube-hostpath") }}
        resources: {}
        {{- else }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: JVM_OPTS
          value: "-XshowSettings:vm -XX:MaxRAMPercentage=80"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config-cm
        volumeMounts:
        {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
          - name: {{ include "oxtrust.fullname" .}}-updatelbip
            mountPath: /scripts
        {{- end }}
        {{- if or ( eq .Values.global.gluuPersistenceType "couchbase" ) ( eq .Values.global.gluuPersistenceType "hybrid" ) }}
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
        {{- end }}
        livenessProbe:
          httpGet:
            path: /identity/restv1/scim-configuration
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 45
        readinessProbe:
          httpGet:
            path: /identity/restv1/scim-configuration
            port: 8080
          initialDelaySeconds: 35
          periodSeconds: 35
      volumes:
      {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
        - name: {{ include "oxtrust.fullname" .}}-updatelbip
          configMap:
            name: {{ .Release.Name }}-updatelbip
      {{- end }}
      {{- if or (eq .Values.global.gluuPersistenceType "couchbase") (eq .Values.global.gluuPersistenceType "hybrid")  }}
        - name: cb-pass
          secret:
            secretName: {{ .Release.Name }}-cb-pass 
        - name: cb-crt 
          secret:
            secretName: {{ .Release.Name }}-cb-crt  
      {{- end }}
      {{- if eq .Values.global.isDomainRegistered "false" }}
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      {{- end }}
