# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: cn-upgrade
version: 2.0.0
kubeVersion: ">=v1.17.0-0"
description: A Helm chart for upgrading gluu server
type: application
keywords:
  - upgrade
  - gluu
home: https://gluu.org/docs/gluu-server
sources:
  - https://gluu.org/docs/gluu-server/upgrade/
  - https://github.com/GluuFederation/docker-upgrade
  - https://github.com/GluuFederation/cloud-native-edition/tree/4.3/pygluu/kubernetes/templates/helm/gluu-upgrade
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "5.0.0"
