apiVersion: v2
name: gluu-upgrade
description: A Helm chart for upgrading gluu server
type: application
version: 1.2.8
appVersion: 4.2.1_02
maintainers:
- name: Gluu
email: support@gluu.org
home: https://gluu.org/docs/gluu-server