# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    # change it to your actual account; the email can be fetched using
    # the following command: `gcloud info | grep Account`
    name: "ACCOUNT"
    apiGroup: rbac.authorization.k8s.io