# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: config-init-load
resources:
  - jobs.yaml
  - roles.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: gluufederation/config-init
    newTag: 4.2.1_01
configMapGenerator:
  - name: gluu-config-cm
    literals:
      - GLUU_OXD_SERVER_URL="oxd-server:8443"
      - GLUU_OXD_BIND_IP_ADDRESSES="*"
      - GLUU_KEY_ROTATION_FORCE="false"
      - GLUU_SSL_CERT_FROM_SECRETS="true"
      - GLUU_KEY_ROTATION_CHECK="3600"
      - GLUU_KEY_ROTATION_INTERVAL="48"
      - GLUU_LDAP_INIT="true"
      - GLUU_LDAP_INIT_HOST="opendj"
      - GLUU_LDAP_INIT_PORT="1636"
      - GLUU_OXTRUST_CONFIG_GENERATION="true"
      - GLUU_REDIS_TYPE="STANDALONE"
      - GLUU_REDIS_URL="redis:6379"
      - GLUU_CERT_ALT_NAME="opendj"
      #- GLUU_CACHE_TYPE="REDIS"
      #-  GLUU_REDIS_URL="redis:6379"
      #-  GLUU_REDIS_TYPE="STANDALONE
      - GLUU_MAX_RAM_PERCENTAGE="75.0"
      - GLUU_SYNC_CASA_MANIFESTS="false"
      - GLUU_OXTRUST_BACKEND="oxtrust:8080"
      - GLUU_JACKRABBIT_SYNC_INTERVAL=300
      - GLUU_JACKRABBIT_URL="http://jackrabbit:8080"
      - GLUU_CONTAINER_METADATA="kubernetes"
      - GLUU_SYNC_SHIB_MANIFESTS=false
      - GLUU_DOCUMENT_STORE_TYPE="JCA"
      - GLUU_JACKRABBIT_ADMIN_ID="admin"
      - GLUU_JACKRABBIT_ADMIN_PASSWORD_FILE="/etc/gluu/conf/jackrabbit_admin_password"
      - GLUU_CACHE_TYPE=GLUUCACHETYPE
      - GLUU_OXTRUST_API_ENABLED=GLUUOXTRUSTAPIENABLED
      - GLUU_OXTRUST_API_TEST_MODE=GLUUOXTRUSTAPITESTMODE
      - GLUU_CASA_ENABLED=GLUUCASAENABBLED
      - GLUU_PASSPORT_ENABLED=GLUUPASSPORTENABLED
      - GLUU_RADIUS_ENABLED=GLUURADIUSENABLED
      - GLUU_SAML_ENABLED=GLUUSAMLENABLED
      - GLUU_CONFIG_KUBERNETES_NAMESPACE="default"
      - GLUU_SECRET_KUBERNETES_NAMESPACE="default"
      - LB_ADDR=LBADDR
      - GLUU_CONFIG_ADAPTER="kubernetes"
      - GLUU_SECRET_ADAPTER="kubernetes"
      - DOMAIN=FQDN
      - GLUU_OXAUTH_BACKEND="oxauth:8080"
      # options: ldap/couchbase/hybrid
      - GLUU_PERSISTENCE_TYPE=PERSISTENCETYPE
      # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
      - GLUU_PERSISTENCE_LDAP_MAPPING=LDAPMAPPING
      # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
      - GLUU_LDAP_URL="opendj:1636"
      # used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
      - GLUU_COUCHBASE_URL=COUCHBASEURL
      - GLUU_COUCHBASE_USER=CBUSER
      - GLUU_COUCHBASE_SUPERUSER=CBSUPER
      - GLUU_COUCHBASE_SUPERUSER_PASSWORD_FILE="/etc/gluu/conf/couchbase_superuser_password"
      - GLUU_COUCHBASE_CERT_FILE="/etc/certs/couchbase.crt"
      - GLUU_COUCHBASE_PASSWORD_FILE="/etc/gluu/conf/couchbase_password"
      - GLUU_OXD_APPLICATION_CERT_CN="oxd-server"
      - GLUU_OXD_ADMIN_CERT_CN="oxd-server"
  - name: config-generate-params
    files:
      - generate.json
