# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radius.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
  LB_ADDR: {{ .Values.global.lbAddr }}
  {{- end }}
  GLUU_CONFIG_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  GLUU_SECRET_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  GLUU_OXAUTH_BACKEND: {{ .Values.configMap.oxauthBackendUrl | quote }}
  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName | quote }}
  GLUU_SECRET_ADAPTER: {{ .Values.global.configSecretAdapter | quote }}
  DOMAIN: {{ .Values.global.domain | quote }}
  GLUU_MAX_RAM_PERCENTAGE: {{ .Values.global.gluuMaxRamPercent | quote }}
  GLUU_PERSISTENCE_TYPE: {{ .Values.global.gluuPersistenceType | quote }}
  # options: default/user/site/cache/statistic used only if GLUU_PERSISTENCE_TYPE is hybrid
  {{- if or (eq .Values.global.gluuPersistenceType "hybrid") (eq .Values.global.gluuPersistenceType "ldap") }}
  GLUU_PERSISTENCE_LDAP_MAPPING: {{ .Values.global.gluuPersistenceLdapMapping | quote }}
  {{- end }}
  {{- if or (eq .Values.global.gluuPersistenceType "ldap") (eq .Values.global.gluuPersistenceType "hybrid")  }}
  # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
  GLUU_LDAP_URL: {{ .Values.global.gluuLdapUrl | quote }}
  {{- else if or (eq .Values.global.gluuPersistenceType "couchbase") (eq .Values.global.gluuPersistenceType "hybrid") }}
  #  used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
  GLUU_COUCHBASE_URL: {{ .Values.global.gluuCouchbaseUrl }}
  GLUU_COUCHBASE_USER: {{ .Values.global.gluuCouchbaseUser }}
  GLUU_COUCHBASE_CERT_FILE: {{ .Values.global.gluuCouchbaseCertFile | quote }}
  GLUU_COUCHBASE_PASSWORD_FILE: {{ .Values.global.gluuCouchbasePassFile | quote }}
  {{- end }}