# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: oxauth
version: 1.8.7
kubeVersion: ">=v1.21.0-0"
description: OAuth Authorization Server, the OpenID Connect Provider, the UMA Authorization Server--this is the main Internet facing component of Gluu. It's the service that returns tokens, JWT's and identity assertions. This service must be Internet facing.
type: application
keywords:
  - Autherization
  - OpenID
home: https://gluu.org/docs/gluu-server
sources:
  - https://github.com/GluuFederation/docker-oxauth
  - https://github.com/GluuFederation/cloud-native-edition/tree/4.3/pygluu/kubernetes/templates/helm/gluu/charts/oxauth
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "4.5.0"
