# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxtrust
  labels:
    APP_NAME: oxtrust
spec:
  serviceName: oxtrust
  replicas: 1
  selector:
    matchLabels:
      app: oxtrust
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        APP_NAME: oxtrust
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: oxtrust
        imagePullPolicy: Always
        image: gluufederation/oxtrust:4.2.1_01
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python3 /scripts/update-lb-ip.py &
              /app/scripts/entrypoint.sh
        resources:
          requests:
            memory: "1000Mi"
            cpu: "1000m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gluu-config-cm
        volumeMounts:
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
          - mountPath: /scripts
            name: update-lb-ip
        livenessProbe:
          httpGet:
            path: /identity/restv1/health-check
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /identity/restv1/health-check
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - FQDN
      volumes:
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt
      - name: update-lb-ip
        configMap:
          name: updatelbip