# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "4.2.3"
home: https://gluu.org/docs/gluu-server
maintainers:
- name: Gluu
email: support@gluu.org
description: A Helm chart for the opendj server
name: opendj
version: 1.4.4