# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# opendj Environament Variables
nameOverride: ""
fullnameOverride: ""
# StatefulSet
# values declaration
replicas: 1
service:
  ldapServiceName: opendj
image:
  repository: gluufederation/wrends
  tag: 4.1.0_01
  pullPolicy: Always
  
persistence:
  size: 5Gi
  accessModes: ReadWriteOnce
  type: DirectoryOrCreate
  dbStorageSize: 5Gi

#servicePorts values used in StatefulSet container
ports:
  ldaps:
    port: 1636
  ldap:
    port: 1389
  replication:
    port: 8989
  admin:
    port: 4444
# VolumeMounts for StatefulSet
# opendj-init vm
volumeMounts:
  config:
    mountPath: /opt/opendj/config
    name: opendj-volume
  ldif: 
    mountPath: /opt/opendj/ldif
    name: opendj-volume
  logs: 
    mountPath: /opt/opendj/logs
    name: opendj-volume
  db: 
    mountPath: /opt/opendj/db
    name: opendj-volume
  flag: 
    mountPath: /flag
    name: opendj-volume
