# Declare variables to be passed into your templates.

replicaCount: 1
dynamicStorage: true

image:
  repository: gluufederation/oxauth
  tag: 4.0.0_04
  pullPolicy: Always

persistence:
  size: 10M
  accessModes: ReadWriteOnce
  storageClassName: ""

# VolumeClaim values
volumeClaim:
  storage: 50M

#ConfigMap values
gluuLdapUrl: opendj:1636
gluuMaxRamFraction: 1

#Resources for the deployment
requests:
  memory: 1000Mi
limits:
  memory: 1536Mi

#ports for the deployment
ports:
  containerPort: 8080

#VolumeMounts
volumeMounts:
  logs:
    mountPath: /opt/gluu/jetty/oxauth/logs
    name: oxauth-volume
  ext:
    mountPath: /opt/gluu/jetty/oxauth/lib/ext
    name: oxauth-volume
  static:
    mountPath: /opt/gluu/jetty/oxauth/custom/static
    name: oxauth-volume
  pages:
    mountPath: /opt/gluu/jetty/oxauth/custom/pages
    name: oxauth-volume