# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.crRotateServiceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cr-rotate.name" . }}
    chart: {{ include "cr-rotate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ include "cr-rotate.name" . }}
    release: {{ .Release.Name }}
