# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casa
  labels:
    APP_NAME: casa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casa
  template:
    metadata:
      labels:
        APP_NAME: casa
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - FQDN
      volumes:
        - name: cb-pass
          secret:
            secretName: cb-pass
        - name: cb-crt
          secret:
            secretName: cb-crt
        - name: update-lb-ip
          configMap:
            name: updatelbip
      containers:
      - name: casa
        imagePullPolicy: Always
        image: gluufederation/casa:4.2.1_01
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python3 /scripts/update-lb-ip.py &
              /app/scripts/entrypoint.sh
        volumeMounts:
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
          - mountPath: /scripts
            name: update-lb-ip
        livenessProbe:
          httpGet:
            path: /casa/health-check
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /casa/health-check
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 25
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: gluu-config-cm