# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# -- Based on the TinyRadius Java library. The implementation ("Gluu Radius") supports RADIUS authentication, but does not provide RADIUS accounting support. RADIUS accounting packets are simply ignored.
# -- Configure the HorizontalPodAutoscaler
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5 ddd0
  # -- metrics if targetCPUUtilizationPercentage is not set
  metrics: []
  # -- Scaling Policies
  behavior: {}
# -- Add custom normal and secret envs to the service
usrEnvs:
  # -- Add custom normal envs to the service
  # variable1: value1
  normal: {}
  # -- Add custom secret envs to the service
  # variable1: value1
  secret: {}
# -- Add custom dns policy
dnsPolicy: ""
# -- Add custom dns config
dnsConfig: {}
image:
  # -- Image pullPolicy to use for deploying.
  pullPolicy: IfNotPresent
  # -- Image  to use for deploying.
  repository: gluufederation/radius
  # -- Image  tag to use for deploying
  tag: 4.3.0_b1
# -- Service replica number.
replicas: 1
# -- Resource specs.
resources:
  limits:
    # -- CPU limit.
    cpu: 700m
    # -- Memory limit.
    memory: 700Mi
  requests:
    # -- CPU request.
    cpu: 700m
    # -- Memory request.
    memory: 700Mi
service:
  type: ClusterIP
  ports:
    tcp-radius-authentication:
      port: 1812
    tcp-radius-accounting:
      port: 1813
    http-jetty-service:
      port: 8080
  # -- Name of the Radius service. Please keep it as default.
  radiusServiceName: radius
# -- Configure the liveness healthcheck for Radius if needed.
livenessProbe:
  # -- Executes interal command healthcheck.
  exec:
    command:
    - cat
    - /tmp/gluu-radius-health
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 20
# -- Configure the readiness healthcheck for the Radius if needed.
readinessProbe:
  # -- Executes interal command healthcheck.
  exec:
    command:
    - cat
    - /tmp/gluu-radius-health
  initialDelaySeconds: 25
  periodSeconds: 25
  timeoutSeconds: 5
  failureThreshold: 20
volumes: []
  # Configure any additional volumes that need to be attached to the pod
volumeMounts: []
  # Configure any additional volumesMounts that need to be attached to the containers

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
