{{- if or (eq .Values.global.gluuPersistenceType "ldap") (eq .Values.global.gluuPersistenceType "hybrid") }}
{{ range $k, $v := until ( .Values.multiCluster.replicaCount | int ) }}
---
# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Service
metadata:
  {{- if $.Values.multiCluster.enabled }}
  name: {{ $.Values.global.ldapServiceName }}-regional-{{$v}}
  {{- else }}
  name: {{ $.Values.global.ldapServiceName }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "opendj.labels" $ | indent 4}}
    {{- if $.Values.multiCluster.enabled }}
    appregion: {{ include "opendj.name" $ }}-regional-{{$v}}
    {{- end }}
spec:
  ports:
  {{- if $.Values.multiCluster.enabled }}
    - port: 1636
      name: tcp-ldaps
      targetPort: 1636
      protocol: TCP
      nodePort: 3063{{$v}}
    - port: 3098{{$v}}
      name: tcp-replication
      targetPort: 3098{{$v}}
      protocol: TCP
      nodePort: 3098{{$v}}
    - port: 3044{{$v}}
      name: tcp-admin
      targetPort: 3044{{$v}}
      nodePort: 3044{{$v}}
      protocol: TCP
    - port: 7946
      name: tcp-serf
      targetPort: 7946
      protocol: TCP
      nodePort: 3094{{$v}}
    - port: 7946
      name: udp-serf
      targetPort: 7946
      protocol: UDP
      nodePort: 3094{{$v}}
  type: NodePort
  {{- else }}
    {{- range $key, $value := $.Values.ports }}
    - port: {{ $value.port }}
      name: {{ $key }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol}}
      {{- if $value.nodePort }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
    {{- end }}
  clusterIP: None
  {{- end }}
  selector:
    {{- if $.Values.multiCluster.enabled }}
    appregion: {{ include "opendj.name" $ }}-regional-{{$v}}
    {{- else }}
    app: {{ include "opendj.name" $ }}
    {{- end }}
{{- end }}
{{- if .Values.multiCluster.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.ldapServiceName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendj.labels" . | indent 4}}
spec:
  ports:
  - port: 1636
    name: tcp-ldaps
    targetPort: 1636
    protocol: TCP
  - port: 1389
    name: tcp-ldap
    targetPort: 1389
    protocol: TCP
  - port: 8989
    name: tcp-replication
    targetPort: 8989
    protocol: TCP
  - port: 4444
    name: tcp-admin
    targetPort: 4444
    protocol: TCP
  - port: 7946
    name: tcp-serf
    targetPort: 7946
    protocol: TCP
  - port: 7946
    name: udp-serf
    targetPort: 7946
    protocol: UDP
  clusterIP: None
  selector:
    app: {{ include "opendj.name" . }}
{{- end }}
{{- end }}