# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
{{- if or (eq .Values.global.gluuPersistenceType "ldap") (eq .Values.global.gluuPersistenceType "hybrid") }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "opendj.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    storage: opendj
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: {{ .Values.global.provisioner }}
parameters:
  {{- if eq .Values.global.provisioner "kubernetes.io/aws-ebs" }}
  type: gp2
  fsType: {{ .Values.global.fsType }}
  {{- else if eq .Values.global.provisioner "kubernetes.io/gce-pd" }}
  type: {{ .Values.global.gcePdStorageType }}
  {{- else if eq .Values.global.provisioner "kubernetes.io/azure-disk" }}
  storageAccountType: {{ .Values.global.azureStorageAccountType }}
  kind: {{ .Values.global.azureStorageKind }}
  {{- else if eq .Values.global.provisioner "dobs.csi.digitalocean.com" }}
  {{- else }}
  pool: {{ .Values.global.pool }}
  fsType: {{ .Values.global.fsType }}
  {{- end }}
allowVolumeExpansion: true
reclaimPolicy: {{ .Values.global.reclaimPolicy }}
mountOptions:
  - debug

{{- end }}