# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxd-server
  template:
    metadata:
      labels:
        APP_NAME: oxd-server
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: oxd-server
        imagePullPolicy: Always
        image: gluufederation/oxd-server:4.2.1_01
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python3 /scripts/update-lb-ip.py &
              /app/scripts/entrypoint.sh
        ports:
        - containerPort: 8443
        - containerPort: 8444
        envFrom:
        - configMapRef:
            name: gluu-config-cm
        volumeMounts:
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
          - mountPath: /scripts
            name: update-lb-ip
        livenessProbe:
          exec:
            command:
              - curl
              - -k
              - https://localhost:8443/health-check
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - curl
              - -k
              - https://localhost:8443/health-check
          initialDelaySeconds: 25
          periodSeconds: 25
        resources:
          requests:
            memory: "400Mi"
            cpu: "1000m"
          limits:
            memory: "400Mi"
            cpu: "1000m"
      volumes:
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt
      - name: update-lb-ip
        configMap:
          name: updatelbip
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - FQDN