# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: oxd-server
resources:
  - services.yaml
  - deployments.yaml
images:
  - name: gluufederation/oxd-server
    newTag: 4.1.0_01
configMapGenerator:
  - name: oxd-server-cm
    literals:
      - GLUU_CONFIG_KUBERNETES_NAMESPACE="default"
      - GLUU_SECRET_KUBERNETES_NAMESPACE="default"
      - USE_CLIENT_AUTHENTICATION_FOR_PAT="true"
      - TRUST_ALL_CERTS="true"
      - TRUST_STORE_PATH=""
      - TRUST_STORE_PASSWORD=""
      - CRYPT_PROVIDER_KEY_STORE_PATH=""
      - CRYPT_PROVIDER_KEY_STORE_PASSWORD=""
      - CRYPT_PROVIDER_DN_NAME=""
      - SUPPORT_GOOGLE_LOGOUT="true"
      - STATE_EXPIRATION_IN_MINUTES="5"
      - NONCE_EXPIRATION_IN_MINUTES="5"
      - PUBLIC_OP_KEY_CACHE_EXPIRATION_IN_MINUTES="60"
      - PROTECT_COMMANDS_WITH_ACCESS_TOKEN="true"
      - UMA2_AUTO_REGISTER_CLAIMS_GATHERING_ENDPOINT_AS_REDIRECT_URI_OF_CLIENT="false"
      - ADD_CLIENT_CREDENTIALS_GRANT_TYPE_AUTOMATICALLY_DURING_CLIENT_REGISTRATION="true"
      - MIGRATION_SOURCE_FOLDER_PATH=""
      - STORAGE="h2"
      - DB_FILE_LOCATION="/opt/oxd-server/data/oxd_db"
      - APPLICATION_CONNECTOR_HTTPS_PORT="8443"
      - APPLICATION_KEYSTORE_PATH="/opt/oxd-server/conf/oxd-server.keystore"
      - APPLICATION_KEYSTORE_PASSWORD="example"
      - APPLICATION_KEYSTORE_VALIDATE_CERTS="false"
      - ADMIN_CONNECTOR_HTTPS_PORT="8444"
      - ADMIN_KEYSTORE_PATH="/opt/oxd-server/conf/oxd-server.keystore"
      - ADMIN_KEYSTORE_PASSWORD="example"
      - ADMIN_KEYSTORE_VALIDATE_CERTS="false"
      - GLUU_LOG_LEVEL="TRACE"
      - XDI_LOG_LEVEL="TRACE"
      - THRESHOLD="TRACE"
      - CURRENT_LOG_FILENAME="/var/log/oxd-server/oxd-server.log"
      - ARCHIVED_FILE_COUNT="7"
      - TIME_ZONE="UTC"
      - MAX_FILE_SIZE="10MB"
      - DEFAULT_SITE_CONFIG_OP_HOST=""
      - DEFAULT_SITE_CONFIG_OP_DISCOVERY_PATH=""
      - DEFAULT_SITE_CONFIG_RESPONSE_TYPES="['code']"
      - DEFAULT_SITE_CONFIG_GRANT_TYPES="['authorization_code']"
      - DEFAULT_SITE_CONFIG_ACR_VALUES="['']"
      - DEFAULT_SITE_CONFIG_SCOPE="['openid', 'profile', 'email']"
      - DEFAULT_SITE_CONFIG_UI_LOCALES="['en']"
      - DEFAULT_SITE_CONFIG_CLAIMS_LOCALES="['en']"
      - DEFAULT_SITE_CONFIG_CONTACTS="[]"
      - APPLICATION_KEYSTORE_CN="oxd_server"
      - ADMIN_KEYSTORE_CN="oxd_server"
      - GLUU_SERVER_HOST=""
      - LB_ADDR=LBADDR