# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxauth.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "oxauth.labels" . | indent 4}}
spec:
  ports:
  - port: {{ .Values.ports.containerPort }}
    name: http-oxauth
  selector:
    app: {{ include "oxauth.name" . }} #oxauth
    