apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs.name" . }}-shared-shib
  namespace: {{ .Release.Namespace }}
  labels:
    app: nfs-shared-shib
spec:
  storageClassName: {{ include "nfs.name" . | quote }}
  accessModes: 
   - {{ .Values.persistence.nfsGce.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.nfsGce.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs.name" . }}
spec:
  storageClassName: ""
  accessModes:
    - {{ .Values.persistence.nfsVolumes.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.nfsVolumes.size }}
