apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.persistence.nfsVolumes.size }}
  accessModes:
    - {{ .Values.persistence.nfsVolumes.accessModes }}
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: {{ include "nfs.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
    path: "/opt/shared-shibboleth-idp"