apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nfs.labels" . | indent 4}}
spec:
  ports:
  {{- range $key, $value := .Values.service.ports}}
    - name: {{ $value.name }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol }}
  {{- end }}
  selector:
    role: {{ include "nfs.name" . }}
