# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "4.2.1_01"
description: A Helm chart for casa
name: casa
version: 1.2.6
maintainers:
- name: Gluu
home: https://gluu.org/docs/casa/
email: support@gluu.org
