# Required environment variables for generating Gluu server initial config
#values for environment variables
orgName: Gluu
adminPass: P@ssw0rd
email: support@gluu.com
countryCode: US
state: TE
city: SLC
ldapType: opendj

nameOverride: ""
fullNameOverride: ""

# VolumeClaim values
volumeClaim:
  storage: 1Gi

image:
  repository: gluufederation/config-init
  tag: 4.1.0_dev

persistence:
  size: 1Gi
  accessModes: ReadWriteOnce
  storageClassName: ""
