# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "key-rotation.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ include "key-rotation.name" . }}
    chart: {{ include "key-rotation.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "key-rotation.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "key-rotation.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "key-rotation.name" . }}

