apiVersion: v1
kind: Service
metadata:
  name: {{ include "key-rotation.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "key-rotation.labels" . | indent 4}}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "key-rotation.name" . }}
    release: {{ .Release.Name }}
