apiVersion: v1
kind: ConfigMap
metadata:
  name: oxd-server-cm
data:
  USE_CLIENT_AUTHENTICATION_FOR_PAT: "true"
  TRUST_ALL_CERTS: "false"
  TRUST_STORE_PATH: ""
  TRUST_STORE_PASSWORD: ""
  CRYPT_PROVIDER_KEY_STORE_PATH: ""
  CRYPT_PROVIDER_KEY_STORE_PASSWORD: ""
  CRYPT_PROVIDER_DN_NAME: ""
  SUPPORT_GOOGLE_LOGOUT: "true"
  STATE_EXPIRATION_IN_MINUTES: "5"
  NONCE_EXPIRATION_IN_MINUTES: "5"
  PUBLIC_OP_KEY_CACHE_EXPIRATION_IN_MINUTES: "60"
  PROTECT_COMMANDS_WITH_ACCESS_TOKEN: "true"
  UMA2_AUTO_REGISTER_CLAIMS_GATHERING_ENDPOINT_AS_REDIRECT_URI_OF_CLIENT: "false"
  ADD_CLIENT_CREDENTIALS_GRANT_TYPE_AUTOMATICALLY_DURING_CLIENT_REGISTRATION: "true"
  MIGRATION_SOURCE_FOLDER_PATH: ""
  STORAGE: "h2"
  DB_FILE_LOCATION: "/opt/oxd-server/data/oxd_db"
  APPLICATION_CONNECTOR_HTTPS_PORT: "8443"
  APPLICATION_KEYSTORE_PATH: "/opt/oxd-server/conf/oxd-server.keystore"
  APPLICATION_KEYSTORE_PASSWORD: "example"
  APPLICATION_KEYSTORE_VALIDATE_CERTS: "false"
  ADMIN_CONNECTOR_HTTPS_PORT: "8444"
  ADMIN_KEYSTORE_PATH: "/opt/oxd-server/conf/oxd-server.keystore"
  ADMIN_KEYSTORE_PASSWORD: "example"
  ADMIN_KEYSTORE_VALIDATE_CERTS: "false"
  GLUU_LOG_LEVEL: "TRACE"
  XDI_LOG_LEVEL: "TRACE"
  THRESHOLD: "TRACE"
  CURRENT_LOG_FILENAME: "/var/log/oxd-server/oxd-server.log"
  ARCHIVED_FILE_COUNT: "7"
  TIME_ZONE: "UTC"
  MAX_FILE_SIZE: "10MB"
  DEFAULT_SITE_CONFIG_OP_HOST: ""
  DEFAULT_SITE_CONFIG_OP_DISCOVERY_PATH: ""
  DEFAULT_SITE_CONFIG_RESPONSE_TYPES: "['code']"
  DEFAULT_SITE_CONFIG_GRANT_TYPES: "['authorization_code']"
  DEFAULT_SITE_CONFIG_ACR_VALUES: "['']"
  DEFAULT_SITE_CONFIG_SCOPE: "['openid', 'profile', 'email']"
  DEFAULT_SITE_CONFIG_UI_LOCALES: "['en']"
  DEFAULT_SITE_CONFIG_CLAIMS_LOCALES: "['en']"
  DEFAULT_SITE_CONFIG_CONTACTS: "[]"
  
---

apiVersion: v1
kind: Service
metadata:
  name: oxd-server
  labels:
    app: oxd-server
spec:
  ports:
  - port: 8444
    name: oxd-server-admin-gui
  - port: 8443
    name: oxd-server-app-connector
  selector:
    app: oxd-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxd-server
  labels:
    app: oxd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxd-server
  template:
    metadata:
      labels:
        app: oxd-server
    spec:
      containers:
      - name: oxd-server
        imagePullPolicy: Always
        image: gluufederation/oxd-server:4.0.0_dev
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8443
        - containerPort: 8444
        envFrom:
        - configMapRef:
            name: oxd-server-cm
