# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: oxshibboleth
version: 1.8.1
kubeVersion: ">=v1.21.0-0"
description: Shibboleth project for the Gluu Server's SAML IDP functionality.
type: application
keywords:
  - SAML
  - Shibboleth
home: https://gluu.org/docs/gluu-server
sources:
  - https://github.com/GluuFederation/docker-oxshibboleth
  - https://github.com/GluuFederation/cloud-native-edition/tree/4.4/pygluu/kubernetes/templates/helm/gluu/charts/oxshibboleth
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "4.5.0"
