# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "4.3.0"
description: oxshibboleth Helm chart 
name: oxshibboleth
version: 1.6.1
maintainers:
- name: Gluu
  email: support@gluu.org
home: https://wwwgluu.org

