# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v2
name: scim
version: 1.8.0
kubeVersion: ">=v1.21.0-0"
description: System for Cross-domain Identity Management (SCIM) version 2.0
type: application
keywords:
  - SCIM
  - API
home: https://gluu.org/docs/gluu-server
sources:
  - https://gluu.org/docs/gluu-server/api-guide/scim-api/
  - https://github.com/GluuFederation/docker-scim
  - https://github.com/GluuFederation/cloud-native-edition/tree/4.4/pygluu/kubernetes/templates/helm/gluu/charts/scim
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "4.4.2"
