apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radius.fullname" . }}
  labels:
    app: {{ include "radius.name" . }}
    chart: {{ include "radius.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "radius.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "radius.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python /scripts/updatelbip.py &
              /app/scripts/entrypoint.sh
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: radius-auth
            containerPort: 1812
          - name: radius-ac
            containerPort: 1813
        envFrom:
          - configMapRef:
              name: {{ include "radius.fullname" . }}
        volumeMounts:
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-cert
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/gluu-radius-health
          initialDelaySeconds: 30
          periodDelaySeconds: 30 
          failureThreshold: 20
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/gluu-radius-health
          initialDelaySeconds: 25
          periodDelaySeconds: 25
          failureThreshold: 20
      {{- if eq .Values.global.isDomainRegistered "false"}}
      hostAliases:
        - ip: {{ .Values.global.nginxIp }}
          hostname:
            - {{ .Values.global.domain }} 
      {{- end }}
      volumes:
      - name: cb-pass 
        secret:
          secretName: {{ include "radius.name" . }}-cb-pass
      - name: cb-cert 
        secret: 
          secretName: {{ include "radius.name" . }}-cb-cert
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
    {{- end }}
