# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oxauth.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.oxAuthServiceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.oxAuthServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.oxAuthServiceName }}
    spec:
      containers:
      - name: {{ template "gluu.fullname" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
        command:
          - /bin/sh
          - -c
          - |
              /usr/bin/python /scripts/updatelbip.py &
              /app/scripts/entrypoint.sh
        {{- end}}
        resources:
          requests:
            memory: {{ .Values.requests.memory }}
          # limits:
          #   memory: {{ .Values.limits.memory }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ template "oxauth.fullname" . }}-cm
        volumeMounts:
        {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
          - name: {{ include "oxauth.fullname" .}}-updatelbip
            mountPath: "/scripts"
        {{- end }}
        livenessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: {{ .Values.ports.containerPort }}
          initialDelaySeconds: 25
          periodSeconds: 25
      {{- if eq .Values.global.isDomainRegistered "false" }}
      hostAliases:
      - ip: {{ .Values.global.nginxIp }}
        hostnames:
        - {{ .Values.global.domain }}
      {{- end }}
      volumes:
      {{- if and (and .Values.global.cloud.enabled (eq .Values.global.isDomainRegistered "false") ) (eq .Values.global.provisioner "kubernetes.io/aws-ebs") }}
      - name: {{ include "oxauth.fullname" . }}-updatelbip
        configMap:
          name: {{ .Release.Name }}-updatelbip
      {{- end }}
