apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxauth.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "oxauth.labels" . | indent 4}}
spec:
  ports:
  - port: {{ .Values.ports.containerPort }}
    name: {{ .Values.global.oxAuthServiceName }}
  selector:
    app: {{ include "oxauth.name" . }} #oxauth
    