# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
# Default values for oxtrust.
replicas: 1

dynamicStorage: true

image:
  repository: gluufederation/oxtrust
  tag: 4.1.0_01
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  clusterIp: None

#resources: 
limits:
  memory: 128Mi
requests:
  memory: 300Mi

#containerPOrt ot connect the container with
containerPort: 8080

    