# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Service
metadata:
  # the name must match the application
  name: {{ .Values.configmap.applicationKeystoreCn | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "oxd-server.labels" . | indent 4 }}
spec:
  ports:
    - port: 8444
      name: {{ include "oxd-server.name" . }}-admin-gui
    - port: 8443
      name: {{ include "oxd-server.name" . }}-app-connector
  selector:
    app: {{ include "oxd-server.name" . }}
