# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
replicaCount: 1
image:
  repository: gluufederation/gluu-gateway-ui
  tag: 4.2.0_dev
  pullPolicy: Always
cloud:
  enabled: true
  isDomainRegistered: "false"
  provider: "aws"

requests:
  memory: 500Mi
  cpu: 500m
limits:
  memory: 500Mi
  cpu: 500m
ports:
  containerPort: 443
loadBalancerIp: ""
dbUser: "konga"
dbAdapter: "postgres"
dbPassword: password
kongAdminUrl: "gg-kong-admin.kong.svc.cluster.local:8444"
dbHost: "postgres.postgres.svc.cluster.local"
dbSsl: "false"
dbPort: "5432"
postgresVersion: "11.1"
sslKeyPath: "/etc/certs/tls.key"
sslCertPath: "/etc/certs/tls.crt"
dbDatabase: "konga"
nodeEnv: "production"
oxdServerUrl: "https://oxd-server.gluu.svc.cluster.local:8443"
opServerUrl: "demoexample.gluu.org"
# Custom client created info
oxdId:
clientId:
clientSecret:
oxdServerVersion: "4.1"
ggHost: "https://demoexample.gluu.org/gg-ui"
ggUiRedirectUrlHost: ""
explicitHost: "0.0.0.0"
ggVersion: "4.1"
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

nginxIngress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - demoexample.gluu.org
  tls:
   - secretName: tls-certificate
     hosts:
       - demoexample.gluu.org
