apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nfs.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.persistence.nfsVolumes.size }}
  accessModes:
    - {{ .Values.persistence.nfsVolumes.accessModes }}
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: nfs.{{ .Values.global.namespace }}.svc.cluster.local  # nfs is from svc {{ include "nfs.name" .}}
    path: "/opt/shared-shibboleth-idp"