# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cr-rotate
  labels:
    APP_NAME: cr-rotote
spec:
  selector:
    matchLabels:
      app: cr-rotate
  template:
    metadata:
      labels:
        APP_NAME: cr-rotate
    spec:
      containers:
      - name: cr-rotate
        imagePullPolicy: Always
        image: gluufederation/cr-rotate:4.2.1_01
        envFrom:
        - configMapRef:
            name: gluu-config-cm
        volumeMounts:
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "200m"
      volumes:
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt