# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: radius
resources:
  - deployments.yaml
  - services.yaml
images:
  - name: gluufederation/radius
    newTag: 4.2.1_01
