apiVersion: v1
kind: Service
metadata:
  name: {{ include "casa.fullname" . }}
  labels:
{{ include "casa.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "casa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
