# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: v1
appVersion: "4.0.1_04"
description: oxtrust Helm chart
name: oxtrust
version: 1.0.0
maintainers:
- name: Gluu
home: https://www.gluu.org/ee
email: support@gluu.org
