apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxtrust
  labels:
    APP_NAME: oxtrust
spec:
  serviceName: oxtrust
  replicas: 1
  selector:
    matchLabels:
      app: oxtrust
  volumeClaimTemplates: []
  template:
    spec:
      containers:
      - name: oxtrust
        imagePullPolicy: Always
        image: gluufederation/oxtrust:4.0.1_03
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: oxtrust-cm
        volumeMounts:
          # name must match the volume name below
          - name: shared-shib
            mountPath: "/opt/shared-shibboleth-idp"
            subPath: shared-shibboleth-idp
          - name: cb-pass
            mountPath: "/etc/gluu/conf/couchbase_password"
            subPath: couchbase_password
          - name: cb-crt
            mountPath: "/etc/certs/couchbase.crt"
            subPath: couchbase.crt           
        livenessProbe:
          httpGet:
            path: /identity/restv1/scim-configuration
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /identity/restv1/scim-configuration
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - FQDN
      volumes:
      - name: shared-shib
        persistentVolumeClaim:
          claimName: shared-shib-pvc
      - name: cb-pass
        secret:
          secretName: cb-pass
      - name: cb-crt
        secret:
          secretName: cb-crt       