apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "persistence.fullname" . }}
data:
  GLUU_OXTRUST_API_ENABLED: {{ .Values.configmap.gluuOxtrustApiEnabled | quote }}
  GLUU_OXTRUST_TEST_MODE: {{ .Values.configmap.gluuOxtrustApiTestMode | quote }}
  # Auto enable installation of some services
  GLUU_CASA_ENABLED: {{ .Values.configmap.gluuCasaEnabled | quote }}
  GLUU_PASSPORT_ENABLED: {{ .Values.configmap.gluuPassportEnabled | quote }}
  GLUU_RADIUS_ENABLED: {{ .Values.configmap.gluuRadiusEnabled | quote }}
  {{- if .Values.global.oxshibboleth.enabled }}
  GLUU_SAML_ENABLED: {{ .Values.configmap.gluuSamlEnabled | quote }}
  {{- end }}

  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName | quote }}
  GLUU_SECRET_ADAPTER: {{ .Values.global.configSecretAdapter | quote }}

  GLUU_PERSISTENCE_TYPE: {{ .Values.global.gluuPersistenceType | quote }}
  # options: default/user/site/cache/statistic used only if GLUU_PERSISTENCE_TYPE is hybrid
  {{- if or (eq .Values.global.gluuPersistenceType "hybrid") (eq .Values.global.gluuPersistenceType "ldap") }}
  GLUU_PERSISTENCE_LDAP_MAPPING: {{ .Values.global.gluuPersistenceLdapMapping | quote }}
  {{- end }}
  {{- if or (eq .Values.global.gluuPersistenceType "ldap") (eq .Values.global.gluuPersistenceType "hybrid")  }}
  # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
  GLUU_LDAP_URL: {{ .Values.global.gluuLdapUrl | quote }}
  {{- else if or (eq .Values.global.gluuPersistenceType "couchbase") (eq .Values.global.gluuPersistenceType "hybrid") }}
  #  used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
  GLUU_COUCHBASE_URL: {{ .Values.global.gluuCouchbaseUrl }}
  GLUU_COUCHBASE_USER: {{ .Values.global.gluuCouchbaseUser }}
  GLUU_COUCHBASE_CERT_FILE: {{ .Values.global.gluuCouchbaseCertFile | quote }}
  GLUU_COUCHBASE_PASSWORD_FILE: {{ .Values.global.gluuCouchbasePassFile | quote }}
  {{- end }}
