# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: v1
appVersion: "4.0.0_01"
description: Radius Helm chart 
name: radius
version: 1.0.0
maintainers:
- name: Gluu
email: support@gluu.org
home: https://www.gluu.org
