apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxd-server.fullname" . }}
  labels:
    app: {{ include "oxd-server.name" . }}
    chart: {{ include "oxd-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8444
      name: {{ include "oxd-server.name" . }}-admin-gui
    - port: 8443
      name: {{ include "oxd-server.name" . }}-app-connector
  selector:
    app: {{ include "oxd-server.name" . }}
    release: {{ .Release.Name }}
