# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
{{- if or (eq .Values.global.gluuPersistenceType "ldap") (eq .Values.global.gluuPersistenceType "hybrid") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opendj.fullname" . }}
  namespace: {{ .Values.global.namespace }}
data:
  GLUU_CONFIG_KUBERNETES_NAMESPACE: {{ .Values.global.namespace | quote }}
  GLUU_SECRET_KUBERNETES_NAMESPACE: {{ .Values.global.namespace | quote }}
  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName | quote }}
  GLUU_SECRET_ADAPTER: {{ .Values.global.configSecretAdapter | quote }}
  GLUU_LDAP_INIT_HOST: {{ .Values.global.ldapServiceName }} #{{ template "gluu.fullname" . }}-service
  GLUU_LDAP_INIT: {{ .Values.gluuLdapInit | quote }} # TODO: To be removed
  GLUU_LDAP_INIT_PORT: {{ .Values.gluuLdapInitPort | quote }}
  GLUU_OXTRUST_CONFIG_GENERATION: {{ .Values.gluuOxtrustConfigGeneration | quote }}
  GLUU_CACHE_TYPE: {{ .Values.global.gluuCacheType | quote }}
  {{- if and (.Values.gluuRedisEnabled) (eq .Values.global.gluuCacheType "REDIS") }}
  GLUU_REDIS_URL: {{ .Values.gluuRedisUrl | quote }}
  GLUU_REDIS_TYPE: {{ .Values.gluuRedisType | quote }}
  {{- end }}
  # must the same as the opendj service name
  GLUU_CERT_ALT_NAME: {{ .Values.global.ldapServiceName }} #{{ template "gluu.fullname" . }}-service

{{- end }}
  