# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "4.2.1_02"
description: A Helm chart for persistence layer for Gluu server
name: persistence
version: 1.2.7
maintainers:
- name: Gluu
email: support@gluu.org
home: https://gluu.org/docs/gluu-server
