kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gluu-rolebinding
  namespace: {{ .Values.global.namespace }}
subjects:
- kind: User
  name: system:serviceaccount:default:default # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # this must be Role or ClusterRole
  name: {{ include "config.name" . }}-gluu-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io