# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: opendj
resources:
  - statefulsets.yaml
  - services.yaml
images:
  - name: gluufederation/wrends
    newTag: 4.1.0_01
configMapGenerator:
  - name: opendj-cm
    literals:
      - GLUU_CONFIG_KUBERNETES_NAMESPACE="default"
      - GLUU_SECRET_KUBERNETES_NAMESPACE="default"
      - GLUU_CONFIG_ADAPTER="kubernetes"
      - GLUU_SECRET_ADAPTER="kubernetes"
      - GLUU_LDAP_INIT="true"
      - GLUU_LDAP_INIT_HOST="opendj"
      - GLUU_LDAP_INIT_PORT="1636"
      - GLUU_OXTRUST_CONFIG_GENERATION="true"
      - GLUU_CACHE_TYPE=GLUUCACHETYPE
      - GLUU_REDIS_TYPE="STANDALONE"
      - GLUU_REDIS_URL="redis:6379"
      - GLUU_CERT_ALT_NAME="opendj"
      # options: ldap/couchbase/hybrid     
      - GLUU_PERSISTENCE_TYPE=PERSISTENCETYPE
      # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
      - GLUU_PERSISTENCE_LDAP_MAPPING=LDAPMAPPING
      #- GLUU_CACHE_TYPE="REDIS"
      #-  GLUU_REDIS_URL="redis:6379"
      #-  GLUU_REDIS_TYPE="STANDALONE"