# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opendj
spec:
  serviceName: opendj
  replicas: 1
  selector:
    matchLabels:
      app: opendj
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        APP_NAME: opendj
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - opendj
              topologyKey: "kubernetes.io/hostname"
      volumes: []
      containers:
      - name: opendj
        imagePullPolicy: Always
        image: gluufederation/wrends:4.2.1_01
        lifecycle:
          preStop:
            exec:
              command: ["python3", "/app/scripts/deregister_peer.py"]
        envFrom:
        - configMapRef:
            name: gluu-config-cm
        ports:
          - containerPort: 1636
            name: ldaps
          - containerPort: 1389
            name: ldap
          - containerPort: 8989
            name: replication
          - containerPort: 4444
            name: admin
          - containerPort: 7946
            name: serf
        volumeMounts:
          - mountPath: /opt/opendj/config
            name: opendj-pvc
            subPath: config
          - mountPath: /opt/opendj/ldif
            name: opendj-pvc
            subPath: ldif
          - mountPath: /opt/opendj/logs
            name: opendj-pvc
            subPath: logs
          - mountPath: /opt/opendj/db
            name: opendj-pvc
            subPath: db
          - mountPath: /flag
            name: opendj-pvc
            subPath: flag
        resources:
          requests:
            memory: "2000Mi"
            cpu: "1500m"
          limits:
            memory: "2000Mi"
            cpu: "1500m"
        livenessProbe:
          exec:
            command:
            - python3
            - /app/scripts/healthcheck.py
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 20
        readinessProbe:
          exec:
            command:
            - python3
            - /app/scripts/healthcheck.py
          initialDelaySeconds: 25
          periodSeconds: 25
          failureThreshold: 20