# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cb-restore-points.fullname" . }}
data:
  restorepoints: {{ .Values.backupRestorePoints | b64enc }}
