apiVersion: v1
kind: Service
metadata:
  name: {{ include "oxd-server.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "oxd-server.labels" . | indent 4 }}
spec:
  ports:
    - port: 8444
      name: {{ include "oxd-server.name" . }}-admin-gui
    - port: 8443
      name: {{ include "oxd-server.name" . }}-app-connector
  selector:
    app: {{ include "oxd-server.name" . }}
    release: {{ .Release.Name }}
