apiVersion: v2
name: ldap-backup
description: A backup strategy for LDAP
type: application
version: 1.4.4
appVersion: "4.2.3"
kubeVersion: ">=v1.17.0-0"
icon: https://www.gluu.org/wp-content/uploads/2020/01/Gluu-Green-Icon-64.png
home: https://www.gluu.org
sources:
  - https://github.com/GluuFederation/cloud-native-edition
maintainers:
- name: moabu
  email: mo@gluu.org


