# License terms and conditions:
# https://www.gluu.org/license/enterprise-edition/
apiVersion: v2
appVersion: 4.0.0
home: https://www.gluu.org/de
maintainers:
- name: Gluu
email: support@gluu.org
description: A Helm chart for Gluu server
name: gluu-server-helm
version: 1.0.0
dependencies:
    - name: config
      condition: global.config.enabled
      version: 1.0.0
  
    - name: redis
      condition: global.redis.enabled
      version: 1.0.0
      tags:
        - redis
  
    - name: opendj
      condition: global.opendj.enabled
      version: 1.0.0
  
    - name: oxauth
      condition: global.oxauth.enabled
      version: 1.0.0
  
    - name: shared-shib
      condition: global.shared-shib.enabled
      version: 1.0.0
  
    - name: oxtrust
      condition: global.oxtrust.enabled
      version: 1.0.0
  
    - name: nginx
      condition: global.nginx.enabled
      version: 1.0.0
  
    - name: oxshibboleth
      condition: global.oxshibboleth.enabled
      version: 1.0.0
  
    - name: oxpassport
      version: 1.0.0
      condition: persistence.configmap.gluuPassportEnabled
      tags:
        - oxpassport

    - name: casa
      version: 1.0.0
      condition: persistence.configmap.gluuCasaEnabled
      tags:
        - casa 
  
    - name: key-rotation
      condition: global.key-rotation.enabled
      version: 1.0.0
      tags:
        - key-rotation
  
    - name: cr-rotate
      version: 1.0.0
      condition: global.cr-rotate.enabled
      tags:
        - cr-rotate
  
    - name: radius
      condition: persistence.configmap.gluuRadiusEnabled
      version: 1.0.0
      tags:
        - radius
  
    - name: nfs
      condition: global.nfs.enabled
      version: 1.0.0
  
    - name: efs-provisioner
      condition: global.efs-provisioner.enabled
      version: 0.7.0
  
    - name: oxd-server
      condition: global.oxd-server.enabled
      version: 1.0.0
  
    - name: persistence
      condition: global.persistence.enabled
      version: 1.0.0
      
  
